<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ReTime_Testing</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>

    <Authors>青色漫地_wait</Authors>
    <Product>ReTime - Testing</Product>
    <Copyright>Copyright © 青色漫地_wait</Copyright>
    <FileVersion>0.0.0.1</FileVersion>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="iNKORE.UI.WPF" Version="1.2.8" />
    <PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.10.2.1" />
  </ItemGroup>

</Project>
